import { v4 as uuid } from 'uuid';

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */
import {
  realMadrid,
  footballBoots,
  sneakers,
  football,
  manchesterUnited,
  barcaJersey,
  liverpoolJersey,
  nikeAirForce,
  nikeAirTempo,
  nikeJordan,
  nikeMercurial,
  nikeMercurialDream,
  nikeMercurialSuperfly,
  nikePhantom,
  nikePresto,
  psgJersey,
  pumaOne,
  nikeVapormax,
  manchesterUnitedAway,
  bayernJersey,
} from './../../assets/index';
export const products = [
  {
    _id: uuid(),
    title: 'Real Madrid Jersey',
    price: '5000',
    categoryName: 'jersey',
    inWishlist: true,
    imgSrc: realMadrid,
    isBestSeller: true,
    rating: 4,
  },
  {
    _id: uuid(),
    title: 'Nike Strike Football',
    price: '3000',
    categoryName: 'football',
    inWishlist: false,
    imgSrc: football,
    rating: 3.5,
  },
  {
    _id: uuid(),
    title: 'Manchecter United Jersey',
    price: '5000',
    inWishlist: true,
    categoryName: 'jersey',
    imgSrc: manchesterUnited,
    rating: 4.5,
  },
  {
    _id: uuid(),
    title: 'Manchecter United Away Jersey',
    price: '4500',
    inWishlist: true,
    categoryName: 'jersey',
    imgSrc: manchesterUnitedAway,
    rating: 4.1,
  },
  {
    _id: uuid(),
    title: 'Barcelona Home Jersey',
    price: '4500',
    inWishlist: true,
    categoryName: 'boots',
    imgSrc: barcaJersey,
    rating: 3.9,
  },
  {
    _id: uuid(),
    title: 'Liverpool Home Jersey',
    price: '3000',
    inWishlist: true,
    categoryName: 'jersey',
    imgSrc: liverpoolJersey,
    rating: 3.8,
  },
  {
    _id: uuid(),
    title: 'Bayern Munich Home Jersey',
    price: '5000',
    inWishlist: true,
    categoryName: 'jersey',
    imgSrc: bayernJersey,
    rating: 4.5,
  },

  {
    _id: uuid(),
    title: 'PSG Away Jersey',
    price: '3000',
    inWishlist: true,
    categoryName: 'jersey',
    imgSrc: liverpoolJersey,
    rating: 2.5,
  },
  {
    _id: uuid(),
    title: 'PSG Away Jersey',
    price: '3000',
    inWishlist: true,
    categoryName: 'jersey',
    imgSrc: psgJersey,
    rating: 2.5,
  },
  {
    _id: uuid(),
    title: 'Nike Jordans 1',
    price: '18000',
    inWishlist: true,
    categoryName: 'sneakers',
    imgSrc: sneakers,
    rating: 4.5,
  },
  {
    _id: uuid(),
    title: 'Nike Air Force 1',
    price: '10000',
    inWishlist: true,
    categoryName: 'sneakers',
    imgSrc: nikeAirForce,
    rating: 4.9,
  },
  {
    _id: uuid(),
    title: 'Nike Air Temp',
    price: '10000',
    inWishlist: true,
    categoryName: 'sneakers',
    imgSrc: nikeAirTempo,
    rating: 3.5,
  },
  {
    _id: uuid(),
    title: 'Nike Presto',
    price: '10000',
    inWishlist: true,
    categoryName: 'sneakers',
    imgSrc: nikePresto,
    rating: 2.5,
  },
  {
    _id: uuid(),
    title: 'Nike VaporMax',
    price: '10000',
    inWishlist: true,
    categoryName: 'sneakers',
    imgSrc: nikeVapormax,
    rating: 4.2,
  },
  {
    _id: uuid(),
    title: 'Nike Jordan 1 ',
    price: '10000',
    inWishlist: true,
    categoryName: 'sneakers',
    imgSrc: nikeJordan,
    rating: 4.9,
  },
  {
    _id: uuid(),
    title: 'Nike Mercurial',
    price: '8000',
    inWishlist: true,
    categoryName: 'boots',
    imgSrc: nikeMercurial,
    rating: 3.1,
  },
  {
    _id: uuid(),
    title: 'Nike Mercurial Dream',
    price: '6000',
    inWishlist: true,
    categoryName: 'boots',
    imgSrc: nikeMercurialDream,
    rating: 3.8,
  },
  {
    _id: uuid(),
    title: 'Nike Mercurial SuperFly',
    price: '6000',
    inWishlist: true,
    categoryName: 'boots',
    imgSrc: nikeMercurialSuperfly,
    rating: 4.2,
  },
  {
    _id: uuid(),
    title: 'Nike Phantom',
    price: '5000',
    inWishlist: true,
    categoryName: 'boots',
    imgSrc: nikePhantom,
    rating: 3.9,
  },
  {
    _id: uuid(),
    title: 'Puma One',
    price: '2000',
    inWishlist: true,
    categoryName: 'boots',
    imgSrc: pumaOne,
    rating: 4,
  },
  {
    _id: uuid(),
    title: 'Nike Mercurial II ',
    price: '3000',
    inWishlist: true,
    categoryName: 'boots',
    imgSrc: footballBoots,
    rating: 2.5,
  },
];
